* Terminology

+ NAT :: Network Address Translation, a method of remapping one IP address space into another by modifying network address information in the IP header of packets while they are in transit across a traffic routing device.

+ IP :: Internet Protocol, the principal communications protocol in the Internet protocol suite for relaying datagrams across network boundaries. Its routing function enables internetworking, and essentially establishes the Internet.

+ IP Address :: a numerical label assigned to each device connected to a computer network that uses the Internet Protocol for communication

+ Ethernet :: a family of computer networking technologies commonly used in local area networks (LAN), metropolitan area networks (MAN) and wide area networks (WAN).

+ Broadcast Address :: a network address at which all devices connected to a multiple-access communications network are enabled to receive datagrams.

+ MAC Address :: Media Access Control address of a device is a unique identifier assigned to a network interface controller for communications at the data link layer of a network segment

+ DHCP Server :: Dynamic Host Configuration Protocol is a network management protocol used on UDP/IP networks whereby a DHCP server dynamically assigns an IP address and other network configuration parameters to each device on a network so they can communicate with other IP networks. A DHCP server enables computers to request IP addresses and networking parameters automatically from the Internet service provider, reducing the need for a network administrator or a user to manually assign IP addresses to all network devices. In the absence of a DHCP server, a computer or other device on the network needs to be manually assigned an IP address, or to assign itself an APIPA address, which will not enable it to communicate outside its local subnet.

+ DNS Server :: Domain Name System is a hierarchical and decentralized naming system for computers, services, or other resources connected to the Internet or a private network. It associates various information with domain names assigned to each of the participating entities
